baseurl = "https://vuhung071290.github.io/"
title = "Culi Code"
theme = "hugo-coder"
languagecode = "vn"
defaultcontentlanguage = "vn"

paginate = 20

[services]
[services.disqus]
disqusShortname = "vuhung071290"

[markup.highlight]
style = "github-dark"

[params]
    author = "Hung Le"
    description = ""
    keywords = "blog,developer,personal"
    info = ""
    avatarurl = "images/avatar.jpg"

    faviconSVG = "/img/favicon.svg"
    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    colorScheme = "auto"
    hidecolorschemetoggle = false

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
    author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa-brands fa-github fa-2x"
    weight = 1
    url = "https://github.com/vuhung071290/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa-brands fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/l%C3%AA-v%C5%A9-h%C3%B9ng-43196ba2/"

[languages]
    [languages.vn]

        [[languages.vn.menu.main]]
        name = "POSTS"
        weight = 1
        url = "/posts/"
