baseurl = "https://vuhung071290.github.io/"
title = "Blog của Hùng"

theme = "hugo-coder"

languagecode = "vn"
defaultcontentlanguage = "vn"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "vuhung071290"

[params]
    author = "Hùng Lê"
    description = "Blog cá nhân của Hùng"
    keywords = "blog,developer,personal"
    info = "Full Stack Dev"
    avatarurl = "images/avatar.jpg"
    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    rtl = false

    # Use inverted colors
    inverted = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/vuhung071290/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/le-vu-hung-43196ba2/"

[languages]
    [languages.vn]
        languagename = "Tiếng Việt"

        [[languages.vn.menu.main]]
        name = "Bài viết"
        weight = 1
        url = "/posts/"

        [[languages.vn.menu.main]]
        name = "Dự án"
        weight = 2
        url = "/projects/"


    [languages.en]
        languagename = "English"
        title = "Hung's blog"

        [languages.en.params]
            author = "Hung Le"
            info = "Full Stack Dev"
            description = "Hung's personal blog"
            keywords = "blog,developer,personal"
            footercontent = ""

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 1
            url = "/en/posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 2
            url = "/en/projects/"
