baseurl = "https://vuhung071290.github.io/"
title = "Blog của Culi Code"

theme = "hugo-coder"

languagecode = "vn"
defaultcontentlanguage = "vn"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "vuhung071290"

[params]
    author = ""
    description = ""
    keywords = "blog,developer,personal"
    info = ""
    avatarurl = "images/avatar.jpg"

    favicon_32 = "images/favicon-32x32.png"
    favicon_16 = "images/favicon-16x16.png"

    footercontent = ""

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hidecolorschemetoggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/vuhung071290/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 2
    url = "https://www.linkedin.com/in/le-vu-hung-43196ba2/"

[languages]
    [languages.vn]

        [[languages.vn.menu.main]]
        name = "Bài viết"
        weight = 1
        url = "/posts/"
